### ISSUE TITLE
Kanadi does not reconnect to nakadi

### ISSUE THREAD

**Issue by Refal** [zalando-incubator/kanadi#80] opened 2019-01-22 13:29 UTC
From logs I can see:
`INFO --- org.zalando.kanadi.api.Subscriptions : Server disconnected Nakadi stream, reconnecting in 30 seconds Old StreamId`
And nothing happens then
Looks like at this line: [https://github.com/zalando-incubator/kanadi/blob/master/src/main/scala/org/zalando/kanadi/api/Subscriptions.scala#L1378](reconnect)
If  exception happened then there is no code to correctly restart stream again

**Comment by mdedetrich** [comment] 2019-02-05 12:35
Found out the cause of this issue, closing

**Closed by mdedetrich** 2019-02-05 12:35 UTC
